Repository UMC-8th-MIRUNI/MIRUNI_Backend, pull requests merged in 2025-08, with the labels that each got.

#66 [feat] cors 설정 추가
  src/main/java/dgu/umc_app/global/config/SecurityConfig.java
  src/main/java/dgu/umc_app/global/config/WebConfig.java
Labels: ✨ feature

#39 [feat] 구글, 카카오 로그인 api 구현
  src/main/java/dgu/umc_app/domain/user/controller/UserAuthApi.java
  src/main/java/dgu/umc_app/domain/user/controller/UserAuthController.java
  src/main/java/dgu/umc_app/domain/user/dto/AuthUserInfoDto.java
  src/main/java/dgu/umc_app/domain/user/dto/UserResponseDto.java
  src/main/java/dgu/umc_app/domain/user/dto/request/GoogleLoginRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/request/GoogleSignUpRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/request/KakaoLoginRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/request/KakaoSignUpRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/request/UserSignupRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/response/AuthLoginResponse.java
  src/main/java/dgu/umc_app/domain/user/entity/Status.java
  src/main/java/dgu/umc_app/domain/user/entity/User.java
  src/main/java/dgu/umc_app/domain/user/exception/AuthErrorCode.java
  src/main/java/dgu/umc_app/domain/user/exception/UserErrorCode.java
  src/main/java/dgu/umc_app/domain/user/repository/UserRepository.java
  src/main/java/dgu/umc_app/domain/user/service/UserCommandService.java
  src/main/java/dgu/umc_app/domain/user/validator/UserValidator.java
  src/main/java/dgu/umc_app/global/authorize/CustomUserDetailService.java
  src/main/java/dgu/umc_app/global/authorize/LoginUserArgumentResolver.java
  src/main/java/dgu/umc_app/global/common/JwtUtil.java
  src/main/java/dgu/umc_app/global/config/JwtFilter.java
  src/main/java/dgu/umc_app/global/config/SecurityConfig.java
  src/main/resources/application-local.yml
Labels: ✨ feature

#71 [fix] #70 알람 주기 설정 필드 삭제
  src/main/java/dgu/umc_app/domain/user/dto/AuthUserInfoDto.java
Labels: 🐛 bug

#72 [deploy] main 브랜치에 병합
  src/main/java/dgu/umc_app/domain/user/dto/AuthUserInfoDto.java
Labels: 🚀 deploy

#73 [ feat ] FCM 토큰 삭제 API를 구현한다
  src/main/java/dgu/umc_app/domain/fcm/entity/FcmErrorResponse.java
  src/main/java/dgu/umc_app/domain/fcm/entity/FcmToken.java
  src/main/java/dgu/umc_app/domain/fcm/repository/FcmTokenRepository.java
  src/main/java/dgu/umc_app/domain/fcm/service/FcmTokenCommandService.java
  src/main/java/dgu/umc_app/domain/fcm/service/FcmTokenQueryService.java
  src/main/java/dgu/umc_app/domain/fcm/service/NotificationScheduleService.java
Labels: ✨ feature

#80 [feat] #77 보관함 페이지 조회, 회고 삭제 API 구현
  src/main/java/dgu/umc_app/domain/plan/repository/AiPlanRepository.java
  src/main/java/dgu/umc_app/domain/plan/repository/PlanRepository.java
  src/main/java/dgu/umc_app/domain/report/controller/ReportApi.java
  src/main/java/dgu/umc_app/domain/report/controller/ReportController.java
  src/main/java/dgu/umc_app/domain/report/dto/response/StoragePageResponse.java
  src/main/java/dgu/umc_app/domain/report/entity/Report.java
  src/main/java/dgu/umc_app/domain/report/repository/ReportRepository.java
  src/main/java/dgu/umc_app/domain/report/service/ReportCommandService.java
  src/main/java/dgu/umc_app/domain/report/service/ReportQueryService.java
  src/main/java/dgu/umc_app/domain/review/controller/ReviewApi.java
  src/main/java/dgu/umc_app/domain/review/controller/ReviewController.java
  src/main/java/dgu/umc_app/domain/review/entity/Mood.java
  src/main/java/dgu/umc_app/domain/review/service/ReviewCommandService.java
  src/main/resources/application-local.yml
Labels: ✨ feature

#64 [fix] #30 일자별 조회 빈 리스트 반환문제 해결 + 총 일정 갯수 계산로직 수정
  src/main/java/dgu/umc_app/domain/plan/controller/PlanApi.java
  src/main/java/dgu/umc_app/domain/plan/controller/PlanController.java
  src/main/java/dgu/umc_app/domain/plan/dto/request/PlanCreateRequest.java
  src/main/java/dgu/umc_app/domain/plan/dto/response/CalendarDayResponse.java
  src/main/java/dgu/umc_app/domain/plan/dto/response/UnfinishedPlanResponse.java
  src/main/java/dgu/umc_app/domain/plan/entity/Plan.java
  src/main/java/dgu/umc_app/domain/plan/repository/AiPlanRepository.java
  src/main/java/dgu/umc_app/domain/plan/repository/PlanRepository.java
  src/main/java/dgu/umc_app/domain/plan/service/PlanCommandService.java
  src/main/java/dgu/umc_app/domain/plan/service/PlanQueryService.java
  src/main/resources/application.yml
Labels: ✨ feature

#89 [feat] #81 일반 일정 회고 저장 API 구현
  src/main/java/dgu/umc_app/domain/review/controller/ReviewApi.java
  src/main/java/dgu/umc_app/domain/review/controller/ReviewController.java
  src/main/java/dgu/umc_app/domain/review/dto/request/ReviewCreateRequest.java
  src/main/java/dgu/umc_app/domain/review/dto/response/ReviewCreateResponse.java
  src/main/java/dgu/umc_app/domain/review/dto/response/ReviewDetailResponse.java
  src/main/java/dgu/umc_app/domain/review/entity/Review.java
  src/main/java/dgu/umc_app/domain/review/repository/ReviewRepository.java
  src/main/java/dgu/umc_app/domain/review/service/ReviewCommandService.java
  src/main/java/dgu/umc_app/domain/review/service/ReviewQueryService.java
Labels: ✨ feature

#101 [fix] main 병합 시 오류 해결
  src/main/java/dgu/umc_app/domain/review/service/ReviewCommandService.java
  src/main/java/dgu/umc_app/global/authorize/TokenService.java
Labels: 🐛 bug, 🚀 deploy

#90 [feat] 일정별 세부 조회 API
  src/main/java/dgu/umc_app/domain/plan/controller/PlanApi.java
  src/main/java/dgu/umc_app/domain/plan/controller/PlanController.java
  src/main/java/dgu/umc_app/domain/plan/dto/request/PlanCreateRequest.java
  src/main/java/dgu/umc_app/domain/plan/dto/response/PlanDetail.java
  src/main/java/dgu/umc_app/domain/plan/dto/response/PlanDetailResponse.java
  src/main/java/dgu/umc_app/domain/plan/repository/AiPlanRepository.java
  src/main/java/dgu/umc_app/domain/plan/repository/PlanRepository.java
  src/main/java/dgu/umc_app/domain/plan/service/PlanCommandService.java
  src/main/java/dgu/umc_app/domain/plan/service/PlanQueryService.java
  src/main/java/dgu/umc_app/domain/review/service/ReviewCommandService.java
  src/main/resources/application-local.yml
Labels: ✨ feature

#92 [feat] #91 일정 수정 API 구현
  src/main/java/dgu/umc_app/domain/plan/controller/PlanApi.java
  src/main/java/dgu/umc_app/domain/plan/controller/PlanController.java
  src/main/java/dgu/umc_app/domain/plan/dto/request/AiPlanUpdate.java
  src/main/java/dgu/umc_app/domain/plan/dto/request/PlanCreateRequest.java
  src/main/java/dgu/umc_app/domain/plan/dto/request/PlanUpdateRequest.java
  src/main/java/dgu/umc_app/domain/plan/dto/response/PlanDetail.java
  src/main/java/dgu/umc_app/domain/plan/dto/response/PlanDetailResponse.java
  src/main/java/dgu/umc_app/domain/plan/entity/AiPlan.java
  src/main/java/dgu/umc_app/domain/plan/entity/Plan.java
  src/main/java/dgu/umc_app/domain/plan/exception/AiPlanErrorCode.java
  src/main/java/dgu/umc_app/domain/plan/service/PlanCommandService.java
Labels: ✨ feature

#103 [feat] #99 pw변경 figma화면에 맞게 api 다시 구현
  build.gradle
  src/main/java/dgu/umc_app/domain/user/controller/UserAuthApi.java
  src/main/java/dgu/umc_app/domain/user/controller/UserAuthController.java
  src/main/java/dgu/umc_app/domain/user/dto/request/PasswordResetRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/request/ResetPasswordRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/request/VerifyResetCodeRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/response/VerifyResponse.java
  src/main/java/dgu/umc_app/domain/user/exception/UserErrorCode.java
  src/main/java/dgu/umc_app/domain/user/service/EmailService.java
  src/main/java/dgu/umc_app/domain/user/service/UserCommandService.java
  src/main/java/dgu/umc_app/global/config/MailConfig.java
  src/main/java/dgu/umc_app/global/config/SchedulerConfig.java
  src/main/java/dgu/umc_app/global/config/SecurityConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/templates/email.html
Labels: ✨ feature

#118 [deploy] main 브랜치에 병합
  .DS_Store
  .github/CODEOWNERS
  .gitignore
  build.gradle
  dump.rdb
  src/main/java/dgu/umc_app/domain/plan/controller/HomeApi.java
  src/main/java/dgu/umc_app/domain/plan/controller/HomeController.java
  src/main/java/dgu/umc_app/domain/plan/controller/PlanApi.java
  src/main/java/dgu/umc_app/domain/plan/controller/PlanController.java
  src/main/java/dgu/umc_app/domain/plan/dto/request/AiPlanUpdate.java
  src/main/java/dgu/umc_app/domain/plan/dto/request/PlanCreateRequest.java
  src/main/java/dgu/umc_app/domain/plan/dto/request/PlanUpdateRequest.java
  src/main/java/dgu/umc_app/domain/plan/dto/response/HomeResponse.java
  src/main/java/dgu/umc_app/domain/plan/dto/response/PlanDetail.java
  src/main/java/dgu/umc_app/domain/plan/dto/response/PlanDetailResponse.java
  src/main/java/dgu/umc_app/domain/plan/entity/AiPlan.java
  src/main/java/dgu/umc_app/domain/plan/entity/Plan.java
  src/main/java/dgu/umc_app/domain/plan/exception/AiPlanErrorCode.java
  src/main/java/dgu/umc_app/domain/plan/repository/AiPlanRepository.java
  src/main/java/dgu/umc_app/domain/plan/repository/PlanRepository.java
  src/main/java/dgu/umc_app/domain/plan/service/PlanCommandService.java
  src/main/java/dgu/umc_app/domain/plan/service/PlanQueryService.java
  src/main/java/dgu/umc_app/domain/review/service/ReviewCommandService.java
  src/main/java/dgu/umc_app/domain/user/controller/UserApi.java
  src/main/java/dgu/umc_app/domain/user/controller/UserAuthApi.java
  src/main/java/dgu/umc_app/domain/user/controller/UserAuthController.java
  src/main/java/dgu/umc_app/domain/user/controller/UserController.java
  src/main/java/dgu/umc_app/domain/user/dto/AuthUserInfoDto.java
  src/main/java/dgu/umc_app/domain/user/dto/request/PasswordResetRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/request/ResetPasswordRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/request/SurveyRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/request/UserSignupRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/request/VerifyResetCodeRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/response/PeanutCountResponse.java
  src/main/java/dgu/umc_app/domain/user/dto/response/SurveyResponse.java
  src/main/java/dgu/umc_app/domain/user/dto/response/UserSurveyResponse.java
  src/main/java/dgu/umc_app/domain/user/dto/response/VerifyResponse.java
  src/main/java/dgu/umc_app/domain/user/entity/DelayLevel.java
  src/main/java/dgu/umc_app/domain/user/entity/DelayReason.java
  src/main/java/dgu/umc_app/domain/user/entity/DelaySituation.java
  src/main/java/dgu/umc_app/domain/user/entity/SurveyStatus.java
  src/main/java/dgu/umc_app/domain/user/entity/User.java
  src/main/java/dgu/umc_app/domain/user/exception/UserErrorCode.java
  src/main/java/dgu/umc_app/domain/user/service/EmailService.java
  src/main/java/dgu/umc_app/domain/user/service/UserCommandService.java
  src/main/java/dgu/umc_app/domain/user/service/UserQueryService.java
  src/main/java/dgu/umc_app/global/config/MailConfig.java
  src/main/java/dgu/umc_app/global/config/SchedulerConfig.java
  src/main/java/dgu/umc_app/global/config/SecurityConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/templates/email.html
Labels: 🚀 deploy

#79 [ feat ] 팝업알람을 구현한다
  src/main/java/dgu/umc_app/domain/fcm/entity/AlarmType.java
  src/main/java/dgu/umc_app/domain/fcm/entity/ReminderType.java
  src/main/java/dgu/umc_app/domain/fcm/service/NotificationScheduleService.java
  src/main/java/dgu/umc_app/domain/plan/entity/AiPlan.java
  src/main/java/dgu/umc_app/domain/plan/entity/Plan.java
  src/main/java/dgu/umc_app/domain/plan/repository/AiPlanRepository.java
  src/main/java/dgu/umc_app/domain/plan/repository/PlanRepository.java
  src/main/java/dgu/umc_app/domain/review/service/ReviewCommandService.java
Labels: ✨ feature

#130 [refactor] PlanDelayRequest 수정 + 땅콩개수 계산 구현
  src/main/java/dgu/umc_app/domain/plan/dto/request/PlanDelayRequest.java
  src/main/java/dgu/umc_app/domain/plan/exception/PlanErrorCode.java
  src/main/java/dgu/umc_app/domain/plan/service/PlanCommandService.java
  src/main/java/dgu/umc_app/domain/user/entity/User.java
Labels: ♻️ refactor

#128 [feat] #116 일정 상태 완료 변경 API 구현
  src/main/java/dgu/umc_app/domain/plan/controller/PlanApi.java
  src/main/java/dgu/umc_app/domain/plan/controller/PlanController.java
  src/main/java/dgu/umc_app/domain/plan/dto/request/PlanFinishRequest.java
  src/main/java/dgu/umc_app/domain/plan/dto/response/PlanFinishResponse.java
  src/main/java/dgu/umc_app/domain/plan/exception/PlanErrorCode.java
  src/main/java/dgu/umc_app/domain/plan/service/PlanCommandService.java
  src/main/java/dgu/umc_app/domain/user/entity/User.java
Labels: ✨ feature

#126 [feat] #61 리포트 조회 API 구현
  src/main/java/dgu/umc_app/domain/plan/repository/AiPlanRepository.java
  src/main/java/dgu/umc_app/domain/report/controller/ReportApi.java
  src/main/java/dgu/umc_app/domain/report/controller/ReportController.java
  src/main/java/dgu/umc_app/domain/report/dto/response/DelayPattern.java
  src/main/java/dgu/umc_app/domain/report/dto/response/EmotionAchievement.java
  src/main/java/dgu/umc_app/domain/report/dto/response/MonthOverMonthDelta.java
  src/main/java/dgu/umc_app/domain/report/dto/response/ReportResponse.java
  src/main/java/dgu/umc_app/domain/report/dto/response/Summary.java
  src/main/java/dgu/umc_app/domain/report/entity/LastMonthReport.java
  src/main/java/dgu/umc_app/domain/report/entity/Report.java
  src/main/java/dgu/umc_app/domain/report/exception/ReportErrorCode.java
  src/main/java/dgu/umc_app/domain/report/repository/LastMonthReportRepository.java
  src/main/java/dgu/umc_app/domain/report/repository/ReportRepository.java
  src/main/java/dgu/umc_app/domain/report/service/LastMonthReportSaveService.java
  src/main/java/dgu/umc_app/domain/report/service/MonthlyResetService.java
  src/main/java/dgu/umc_app/domain/report/service/ReportOpenService.java
  src/main/java/dgu/umc_app/domain/report/service/ReportQueryService.java
  src/main/java/dgu/umc_app/domain/report/service/SimpleKeywordService.java
  src/main/java/dgu/umc_app/domain/review/controller/ReviewController.java
  src/main/java/dgu/umc_app/domain/review/repository/ReviewRepository.java
  src/main/java/dgu/umc_app/domain/user/entity/User.java
  src/main/java/dgu/umc_app/domain/user/repository/UserRepository.java
  src/main/resources/application-local.yml
Labels: ✨ feature

#144 [feat] #141 일정 삭제하기 API 구현
  src/main/java/dgu/umc_app/domain/plan/controller/PlanApi.java
  src/main/java/dgu/umc_app/domain/plan/controller/PlanController.java
  src/main/java/dgu/umc_app/domain/plan/dto/request/PlanDeleteRequest.java
  src/main/java/dgu/umc_app/domain/plan/dto/response/PlanDeleteResponse.java
  src/main/java/dgu/umc_app/domain/plan/exception/AiPlanErrorCode.java
  src/main/java/dgu/umc_app/domain/plan/exception/PlanErrorCode.java
  src/main/java/dgu/umc_app/domain/plan/repository/AiPlanRepository.java
  src/main/java/dgu/umc_app/domain/plan/repository/PlanRepository.java
  src/main/java/dgu/umc_app/domain/plan/service/PlanCommandService.java
Labels: ✨ feature

#135 [ refactor ] 스웨거 문서를 깔끔하게 리팩토링 한다
  src/main/java/dgu/umc_app/domain/plan/controller/HomeApi.java
  src/main/java/dgu/umc_app/domain/plan/controller/PlanApi.java
  src/main/java/dgu/umc_app/domain/plan/dto/request/AiPlanUpdate.java
  src/main/java/dgu/umc_app/domain/plan/dto/request/PlanCreateRequest.java
  src/main/java/dgu/umc_app/domain/plan/dto/request/PlanSplitRequest.java
  src/main/java/dgu/umc_app/domain/report/controller/ReportApi.java
  src/main/java/dgu/umc_app/domain/review/controller/ReviewApi.java
  src/main/java/dgu/umc_app/domain/review/dto/request/ReviewCreateRequest.java
  src/main/java/dgu/umc_app/domain/review/dto/request/ReviewUpdateRequest.java
  src/main/java/dgu/umc_app/domain/user/controller/UserApi.java
  src/main/java/dgu/umc_app/domain/user/controller/UserAuthApi.java
  src/main/java/dgu/umc_app/domain/user/dto/request/ChangePasswordRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/request/GoogleLoginRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/request/GoogleSignUpRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/request/KakaoLoginRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/request/KakaoSignUpRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/request/PasswordResetRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/request/ReissueTokenRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/request/ResetPasswordRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/request/SurveyRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/request/UserLoginRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/request/UserSignupRequest.java
  src/main/java/dgu/umc_app/domain/user/dto/request/VerifyResetCodeRequest.java
  src/main/resources/application-local.yml
Labels: ♻️ refactor

#146 [deploy] main 브랜치에 병합
  README.md
  image/umc-miruni_arc.png
  src/main/java/dgu/umc_app/domain/fcm/controller/FcmController.java
  src/main/java/dgu/umc_app/domain/plan/controller/HomeController.java
  src/main/java/dgu/umc_app/domain/plan/controller/PlanApi.java
  src/main/java/dgu/umc_app/domain/plan/controller/PlanController.java
  src/main/java/dgu/umc_app/domain/report/controller/ReportController.java
  src/main/java/dgu/umc_app/domain/review/controller/ReviewController.java
  src/main/java/dgu/umc_app/domain/user/controller/UserAuthController.java
Labels: 🚀 deploy

#152 [feat] #148 문의 남기기 API 수정
  src/main/java/dgu/umc_app/domain/question/controller/UserQuestionApi.java
  src/main/java/dgu/umc_app/domain/question/dto/request/CreateUserQuestionRequestDto.java
  src/main/java/dgu/umc_app/domain/question/dto/response/CreateUserQuestionResponseDto.java
  src/main/java/dgu/umc_app/domain/question/entity/Answer.java
  src/main/java/dgu/umc_app/domain/question/entity/QuestionCategory.java
  src/main/java/dgu/umc_app/domain/question/entity/UserQuestion.java
  src/main/java/dgu/umc_app/domain/question/exception/QuestionErrorCode.java
  src/main/java/dgu/umc_app/domain/question/service/UserQuestionCommandService.java
Labels: ✨ feature

#153 [feat] #147 일정 숨기기 구현
  src/main/java/dgu/umc_app/domain/plan/controller/PlanApi.java
  src/main/java/dgu/umc_app/domain/plan/controller/PlanController.java
  src/main/java/dgu/umc_app/domain/plan/entity/Plan.java
  src/main/java/dgu/umc_app/domain/plan/repository/AiPlanRepository.java
  src/main/java/dgu/umc_app/domain/plan/repository/PlanRepository.java
  src/main/java/dgu/umc_app/domain/plan/service/HomeQueryService.java
  src/main/java/dgu/umc_app/domain/plan/service/PlanCommandService.java
Labels: ✨ feature

#154 [ feat ] 배너/팝업 알람 호출
  src/main/java/dgu/umc_app/domain/plan/service/PlanCommandService.java
  src/main/resources/application-local.yml
Labels: ✨ feature
